<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rafael Santamaría Heredia | A01646667">
<meta name="author" content="Grethel Hernández Olivares | A01640912">
<meta name="author" content="Matías Alfredo Hidalgo Guzmán | A01641323">
<meta name="author" content="Daniel Rodríguez Peralta | A01646867">

<title>Análisis Probabilístico de la Enfermedad Renal Crónica mediante Redes Bayesianas Gaussianas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="ARTICULO2_RBG_files/libs/clipboard/clipboard.min.js"></script>
<script src="ARTICULO2_RBG_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ARTICULO2_RBG_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ARTICULO2_RBG_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="ARTICULO2_RBG_files/libs/quarto-html/popper.min.js"></script>
<script src="ARTICULO2_RBG_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ARTICULO2_RBG_files/libs/quarto-html/anchor.min.js"></script>
<link href="ARTICULO2_RBG_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ARTICULO2_RBG_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ARTICULO2_RBG_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ARTICULO2_RBG_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ARTICULO2_RBG_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#métodos" id="toc-métodos" class="nav-link" data-scroll-target="#métodos">Métodos</a>
  <ul class="collapse">
  <li><a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos">Datos</a></li>
  <li><a href="#preprocesamiento" id="toc-preprocesamiento" class="nav-link" data-scroll-target="#preprocesamiento">Preprocesamiento</a></li>
  <li><a href="#estructuras-candidatas-dags" id="toc-estructuras-candidatas-dags" class="nav-link" data-scroll-target="#estructuras-candidatas-dags">Estructuras candidatas (DAGs)</a></li>
  <li><a href="#ajuste-y-evaluación-de-las-redes-bayesianas-gaussianas" id="toc-ajuste-y-evaluación-de-las-redes-bayesianas-gaussianas" class="nav-link" data-scroll-target="#ajuste-y-evaluación-de-las-redes-bayesianas-gaussianas">Ajuste y evaluación de las Redes Bayesianas Gaussianas</a></li>
  <li><a href="#extensión-con-variables-categóricas" id="toc-extensión-con-variables-categóricas" class="nav-link" data-scroll-target="#extensión-con-variables-categóricas">Extensión con variables categóricas</a></li>
  <li><a href="#modelos-no-paramétricos" id="toc-modelos-no-paramétricos" class="nav-link" data-scroll-target="#modelos-no-paramétricos">Modelos no paramétricos</a></li>
  <li><a href="#consultas-queries" id="toc-consultas-queries" class="nav-link" data-scroll-target="#consultas-queries">Consultas (queries)</a></li>
  </ul></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados">Resultados</a>
  <ul class="collapse">
  <li><a href="#comparación-de-bic-y-aic-entre-estructuras" id="toc-comparación-de-bic-y-aic-entre-estructuras" class="nav-link" data-scroll-target="#comparación-de-bic-y-aic-entre-estructuras">Comparación de BIC y AIC entre estructuras</a></li>
  <li><a href="#resultados-de-las-consultas" id="toc-resultados-de-las-consultas" class="nav-link" data-scroll-target="#resultados-de-las-consultas">Resultados de las consultas</a></li>
  <li><a href="#modelo-mixto-con-variables-categóricas" id="toc-modelo-mixto-con-variables-categóricas" class="nav-link" data-scroll-target="#modelo-mixto-con-variables-categóricas">Modelo mixto con variables categóricas</a></li>
  <li><a href="#modelos-no-paramétricos-1" id="toc-modelos-no-paramétricos-1" class="nav-link" data-scroll-target="#modelos-no-paramétricos-1">Modelos no paramétricos</a></li>
  </ul></li>
  <li><a href="#discusión" id="toc-discusión" class="nav-link" data-scroll-target="#discusión">Discusión</a>
  <ul class="collapse">
  <li><a href="#comparación-de-estructuras" id="toc-comparación-de-estructuras" class="nav-link" data-scroll-target="#comparación-de-estructuras">Comparación de estructuras</a></li>
  <li><a href="#interpretación-de-las-consultas" id="toc-interpretación-de-las-consultas" class="nav-link" data-scroll-target="#interpretación-de-las-consultas">Interpretación de las consultas</a></li>
  <li><a href="#variables-categóricas" id="toc-variables-categóricas" class="nav-link" data-scroll-target="#variables-categóricas">Variables categóricas</a></li>
  <li><a href="#modelos-no-paramétricos-2" id="toc-modelos-no-paramétricos-2" class="nav-link" data-scroll-target="#modelos-no-paramétricos-2">Modelos no paramétricos</a></li>
  <li><a href="#articulación-de-los-hallazgos" id="toc-articulación-de-los-hallazgos" class="nav-link" data-scroll-target="#articulación-de-los-hallazgos">Articulación de los hallazgos</a></li>
  <li><a href="#limitaciones" id="toc-limitaciones" class="nav-link" data-scroll-target="#limitaciones">Limitaciones</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análisis Probabilístico de la Enfermedad Renal Crónica mediante Redes Bayesianas Gaussianas</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Rafael Santamaría Heredia | A01646667 </p>
             <p>Grethel Hernández Olivares | A01640912 </p>
             <p>Matías Alfredo Hidalgo Guzmán | A01641323 </p>
             <p>Daniel Rodríguez Peralta | A01646867 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Este trabajo implementa un modelo probabilístico —una red bayesiana gaussiana (GBN)— para comprender cómo distintos biomarcadores clínicos influyen en el diagnóstico de la enfermedad renal crónica (ERC) y para responder consultas probabilísticas de relevancia clínica. Se utilizó el <em>Chronic Kidney Disease Dataset</em>, restringido a sus once variables continuas sobre una submuestra de 214 casos completos. A partir de entrevistas con tres especialistas del entorno médico se construyeron tres estructuras candidatas (DAGs), que comparten un núcleo causal común —la edad como origen, la presión arterial y la glucosa como factores de riesgo intermedios, y un eje hematológico como consecuencia del daño renal— pero difieren en la ubicación de la creatinina sérica y en el número y disposición de los arcos. Las tres redes se ajustaron por máxima verosimilitud y se evaluaron con los criterios BIC y AIC. La estructura que ubica a la creatinina sérica como único punto de convergencia (DAG 1) obtuvo el mejor ajuste en ambos criterios, pese a no ser la más compleja de las tres.</p>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>La enfermedad renal crónica (ERC) es el deterioro progresivo y a largo plazo de la función renal: los riñones pierden gradualmente su capacidad de filtrar desechos y regular el equilibrio de líquidos y electrolitos del cuerpo. Es un problema de salud pública de gran magnitud: la prevalencia global se estima entre 8% y 16% de la población, y se calcula que uno de cada diez adultos en el mundo tiene algún grado de ERC. Un dato preocupante es que la enfermedad avanza de forma silenciosa, ya que nueve de cada diez adultos con ERC no saben que la padecen, lo que hace crítica la detección temprana.</p>
<p>Las dos causas principales son ampliamente reconocidas: la diabetes mellitus explica alrededor del 48.5% de los casos, y la hipertensión arterial cerca del 19%. Fisiológicamente, la hipertensión daña los vasos sanguíneos que irrigan los riñones y compromete su capacidad de filtrado, mientras que la diabetes provoca que el exceso de glucosa en sangre dañe progresivamente los filtros renales. Esta relación causal —edad, presión arterial y glucosa como antecedentes que derivan en daño renal medible por biomarcadores como la creatinina sérica— es precisamente la estructura que buscamos capturar con un modelo probabilístico.</p>
<p>El diagnóstico de ERC no depende de un solo valor de laboratorio, sino de la interacción entre múltiples biomarcadores (creatinina, urea, hemoglobina, potasio, sodio, entre otros) que están relacionados entre sí de manera causal y no siempre lineal. Un enfoque de caja negra pierde información valiosa sobre cómo estas variables se influyen unas a otras.</p>
<p>Una red bayesiana gaussiana (GBN) resuelve esto de dos formas complementarias: primero, modela explícitamente la incertidumbre, ya que en vez de dar una predicción puntual entrega distribuciones de probabilidad completas, lo que permite responder preguntas del tipo “¿qué tan probable es que la creatinina esté elevada dado que el paciente tiene cierta edad y presión arterial?”, algo especialmente útil para apoyar decisiones clínicas donde rara vez hay certeza absoluta; y segundo, representa relaciones causales interpretables, la estructura de grafo dirigido (DAG) permite trazar visualmente cómo el envejecimiento y los factores de riesgo (presión arterial, glucosa) impactan la función renal, y cómo esta a su vez repercute en marcadores hematológicos secundarios como la anemia.</p>
<p>Esto conecta directamente con el reconocimiento de patrones: la red no solo predice, sino que expone la arquitectura de dependencias entre variables, permitiendo un diagnóstico temprano basado en evidencia observable (biomarcadores) en lugar de esperar síntomas avanzados.</p>
<p>El objetivo de este trabajo es implementar un modelo probabilístico —una red bayesiana gaussiana— que ayude a comprender cómo diferentes biomarcadores influyen en el diagnóstico de la enfermedad renal crónica, y utilizar dicho modelo para responder consultas probabilísticas de relevancia clínica.</p>
<p>El resto del artículo se organiza de la siguiente manera. La sección de Métodos describe el conjunto de datos y su preprocesamiento, el proceso de entrevistas mediante el cual se construyeron las tres estructuras candidatas, el ajuste y los criterios de evaluación de las redes, así como las dos extensiones exploradas: la incorporación de variables categóricas mediante una red condicional-gaussiana y la relajación del supuesto de linealidad mediante un modelo no paramétrico basado en splines. La sección de Resultados presenta los valores de BIC y AIC obtenidos para cada estructura, las respuestas a las consultas planteadas por las especialistas y las métricas de ajuste de ambas extensiones. La sección de Discusión interpreta estos hallazgos a la luz de la literatura clínica y estadística, incluyendo la justificación formal de las consultas que no resultaron resolubles con la mejor estructura. Finalmente, se presentan las conclusiones y las limitaciones del estudio.</p>
</section>
<section id="métodos" class="level2">
<h2 class="anchored" data-anchor-id="métodos">Métodos</h2>
<section id="datos" class="level3">
<h3 class="anchored" data-anchor-id="datos">Datos</h3>
<p>El conjunto de datos utilizado corresponde al <em>Chronic Kidney Disease Dataset</em> del UCI Machine Learning Repository (Rubini et al., 2015), que contiene registros clínicos de 400 pacientes con y sin diagnóstico de enfermedad renal crónica. Cada registro incluye variables demográficas, resultados de análisis de sangre y orina, y comorbilidades reportadas.</p>
<p>Dado que una red bayesiana gaussiana asume que cada nodo sigue una distribución normal condicionada a sus padres, el modelo principal se restringió a las once variables continuas del conjunto: edad (<code>age</code>), presión arterial (<code>bp</code>), glucosa en sangre aleatoria (<code>bgr</code>), urea en sangre (<code>bu</code>), creatinina sérica (<code>sc</code>), sodio (<code>sod</code>), potasio (<code>pot</code>), hemoglobina (<code>hemo</code>), volumen de células empacadas (<code>pcv</code>), conteo de glóbulos blancos (<code>wc</code>) y conteo de glóbulos rojos (<code>rc</code>).</p>
<p>Se excluyeron del modelo principal las variables categóricas del conjunto original, así como tres variables que, pese a estar codificadas numéricamente, corresponden a escalas semicuantitativas y no a mediciones continuas: la densidad urinaria (<code>sg</code>), que toma únicamente cinco valores discretos, y la albúmina (<code>al</code>) y el azúcar en orina (<code>su</code>), reportadas como grados de tira reactiva en una escala ordinal de 0 a 5. Modelar estas variables como nodos gaussianos habría violado el supuesto distribucional de la GBN. Las variables de diabetes (<code>dm</code>) e hipertensión (<code>htn</code>) se reservaron para la extensión con variables categóricas descrita más adelante.</p>
</section>
<section id="preprocesamiento" class="level3">
<h3 class="anchored" data-anchor-id="preprocesamiento">Preprocesamiento</h3>
<p>El archivo original presentaba contaminación de formato que impedía la lectura correcta de varias columnas: caracteres de tabulación y espacios en blanco antepuestos a los valores, así como el carácter <code>?</code> empleado como marcador de dato faltante. Esta contaminación afectaba particularmente a <code>pcv</code>, <code>wc</code> y <code>rc</code>, que eran interpretadas como texto en lugar de como variables numéricas. El preprocesamiento normalizó estos campos y unificó los marcadores de ausencia bajo un valor <code>NA</code> consistente.</p>
<p>Adicionalmente se identificaron tres registros con valores fisiológicamente imposibles: un valor de sodio de 4.5 mEq/L y dos valores de potasio de 39 y 47 mEq/L. Considerando que los rangos de referencia son de 135 a 145 mEq/L para el sodio y de 3.5 a 5.5 mEq/L para el potasio, y que las concentraciones registradas resultan incompatibles con la vida, se interpretaron como errores de captura y se marcaron como datos faltantes. Esta decisión constituye una intervención deliberada sobre los datos y se documenta explícitamente por transparencia metodológica.</p>
<p>El conjunto presenta una proporción considerable de valores faltantes, concentrada en las variables hematológicas: conteo de glóbulos rojos (32.8%), conteo de glóbulos blancos (26.5%), potasio (22.5%), sodio (22.0%) y volumen de células empacadas (17.8%). Las restantes presentan porcentajes menores, desde 13.0% en hemoglobina hasta 2.2% en edad.</p>
<p>Se optó por un análisis de casos completos, que conserva 214 de los 400 registros originales (53.5%). Esta decisión responde a que el ajuste de una red bayesiana gaussiana mediante <code>bn.fit</code> requiere observaciones completas, y a que la imputación introduciría dependencias artificiales entre variables que son precisamente el objeto de estudio del modelo: imputar el valor de un biomarcador a partir de los demás presupondría una estructura de relaciones que el análisis busca inferir. La misma submuestra se empleó para ajustar las tres estructuras, garantizando que los valores de BIC y AIC sean comparables entre modelos al estar calculados sobre el mismo tamaño muestral.</p>
</section>
<section id="estructuras-candidatas-dags" class="level3">
<h3 class="anchored" data-anchor-id="estructuras-candidatas-dags">Estructuras candidatas (DAGs)</h3>
<p>Se realizaron entrevistas con tres personas del entorno médico familiar; la mamá de Grethel, la tía de Matías Hidalgo, ambas médicas, y una prima de Daniel Rodríguez, estudiante próxima a egresar de la carrera de Medicina, a quienes se les explicó el concepto de una DAG y con quienes se construyó cada estructura de manera conjunta, discutiendo la justificación clínica de cada relación de dependencia propuesta sobre las mismas once variables: edad, presión arterial, glucosa en sangre (aleatoria), creatinina sérica, urea en sangre, sodio, potasio, hemoglobina, volumen de células empacadas y conteo de glóbulos blancos y rojos. Las tres estructuras comparten un núcleo causal común: la edad como origen, la presión arterial y la glucosa en sangre como factores de riesgo intermedios, y el eje hematológico hemoglobina → volumen de células empacadas → conteo de glóbulos rojos como consecuencia del daño renal. Sin embargo, difieren en aspectos clave: la primera entrevistada ubicó a la creatinina sérica como único punto de convergencia por el que pasan todas las demás variables; la segunda limitó la influencia de la edad únicamente a la presión arterial, argumentando que la glucosa depende más de estilo de vida y genética que del envejecimiento, y propuso que tanto la glucosa en sangre como el conteo de glóbulos blancos inciden directamente sobre la creatinina sérica sin variables intermedias; mientras que la tercera planteó la estructura más elaborada, sugiriendo que la hiperglucemia crónica afecta al conteo de glóbulos blancos sin mediación del riñón, que la hemoglobina depende de tres variables (urea en sangre, conteo de glóbulos blancos y sodio) en lugar de una sola, reflejando el carácter multifactorial de la anemia renal, y añadiendo una relación entre potasio y sodio no considerada por las otras dos especialistas.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/figures/dag1_ckd.png" class="img-fluid figure-img"></p>
<figcaption><strong>DAG 1</strong> — creatinina sérica como punto único de convergencia.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/figures/dag2_ckd.png" class="img-fluid figure-img"></p>
<figcaption><strong>DAG 2</strong> — glucosa y leucocitos con incidencia directa sobre creatinina.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/figures/dag3_ckd.png" class="img-fluid figure-img"></p>
<figcaption><strong>DAG 3</strong> — anemia renal como fenómeno multifactorial.</figcaption>
</figure>
</div>
</section>
<section id="ajuste-y-evaluación-de-las-redes-bayesianas-gaussianas" class="level3">
<h3 class="anchored" data-anchor-id="ajuste-y-evaluación-de-las-redes-bayesianas-gaussianas">Ajuste y evaluación de las Redes Bayesianas Gaussianas</h3>
<p>Para cada una de las tres estructuras propuestas se ajustó una red bayesiana gaussiana mediante la función <code>bn.fit()</code> del paquete <code>bnlearn</code>, que estima los parámetros de cada distribución local por máxima verosimilitud. En una GBN, la distribución local de cada nodo corresponde a un modelo lineal gaussiano en el que los nodos padre actúan como variables explicativas: el nodo se distribuye normalmente con una media que es combinación lineal de sus padres y una varianza propia que no depende de ellos. Los nodos sin padres se modelan como distribuciones normales univariadas marginales.</p>
<p>Las tres redes se ajustaron sobre la misma submuestra de 214 casos completos. Esta condición es necesaria para que la comparación sea válida: tanto el BIC como el AIC dependen del tamaño muestral, de modo que ajustar cada estructura sobre un subconjunto distinto de observaciones produciría valores no comparables entre sí, y las diferencias reflejarían el cambio de muestra en lugar de la calidad de la estructura.</p>
<p>La evaluación se realizó mediante dos criterios de información. Ambos combinan la log-verosimilitud alcanzada por el modelo con una penalización que crece con el número de parámetros, de manera que un modelo con más arcos sólo obtiene mejor puntaje si la ganancia en ajuste supera el costo de la complejidad añadida. La diferencia entre ambos está en la severidad de esa penalización: el AIC penaliza cada parámetro con un peso constante, mientras que el BIC lo pondera por el logaritmo del tamaño muestral, resultando más estricto y favoreciendo estructuras más parsimoniosas.</p>
<p>Conviene señalar una particularidad de la implementación. La formulación de <code>bnlearn</code> corresponde a</p>
<p><span class="math display">\text{BIC}_{\texttt{bnlearn}} = \ell(\hat{\boldsymbol{\theta}}; \boldsymbol{x}) - \frac{k}{2}\log(n),</span></p>
<p>donde <span class="math inline">\ell</span> es la log-verosimilitud, <span class="math inline">k</span> el número de parámetros y <span class="math inline">n</span> el tamaño muestral. Al expresarse como la log-verosimilitud menos la penalización, y no como su negativo multiplicado por dos, un valor <strong>mayor</strong> indica mejor ajuste. Esta convención es opuesta a la de las funciones <code>BIC()</code> y <code>AIC()</code> de R base, y se mantiene de forma consistente en todas las tablas de este trabajo.</p>
</section>
<section id="extensión-con-variables-categóricas" class="level3">
<h3 class="anchored" data-anchor-id="extensión-con-variables-categóricas">Extensión con variables categóricas</h3>
<p>Una GBN requiere que todos sus nodos sean continuos y normalmente distribuidos, por lo que las variables categóricas del conjunto de datos quedan excluidas del modelo principal. Sin embargo, esta restricción puede relajarse mediante las redes bayesianas condicional-gaussianas (CLG), que admiten nodos discretos y continuos en una misma estructura.</p>
<p>En una red CLG la coexistencia de ambos tipos de nodo no es arbitraria: las variables discretas sólo pueden ser nodos raíz o padres de nodos continuos, nunca hijos de ellos. La razón es que la distribución de un nodo continuo puede condicionarse a las categorías de un padre discreto —ajustando una distribución gaussiana distinta para cada combinación de niveles—, mientras que la operación inversa no está definida dentro de este marco. Los nodos continuos con padres discretos siguen entonces una distribución normal cuya media varía según el nivel del padre categórico.</p>
<p>Para explorar esta extensión se amplió la mejor estructura identificada con las dos comorbilidades más relevantes para la enfermedad renal crónica y que se encuentran disponibles en el conjunto de datos: diabetes mellitus (<code>dm</code>) e hipertensión arterial (<code>htn</code>). Ambas se incorporaron como nodos raíz de tipo factor, conectados a los nodos continuos mediante cuatro arcos con sustento clínico: <code>dm</code> → <code>bgr</code>, dado que la diabetes se manifiesta directamente en niveles elevados de glucosa en sangre; <code>htn</code> → <code>bp</code>, puesto que la hipertensión se define por valores altos de presión arterial; y <code>dm</code> → <code>sc</code> junto con <code>htn</code> → <code>sc</code>, reflejando que ambas condiciones deterioran progresivamente la función renal y elevan la creatinina sérica.</p>
<p>El modelo mixto se ajustó con <code>bn.fit()</code> sobre 212 casos completos —dos menos que el modelo principal, debido a registros con valores faltantes en las variables categóricas— y se evaluó con los criterios <code>bic-cg</code> y <code>aic-cg</code>, las versiones para redes condicional-gaussianas de los criterios empleados anteriormente.</p>
</section>
<section id="modelos-no-paramétricos" class="level3">
<h3 class="anchored" data-anchor-id="modelos-no-paramétricos">Modelos no paramétricos</h3>
<p>La GBN impone que cada nodo hijo sea una combinación lineal de sus padres. Un modelo no paramétrico relaja ese supuesto: si <span class="math inline">y</span> es un nodo hijo y <span class="math inline">\boldsymbol{x} = (x_1, \dots, x_p)</span> son sus nodos padre, la relación se describe como</p>
<p><span class="math display">y \sim \text{N}\left(f_1(x_1) + \dots + f_p(x_p),\ \sigma^2\right),</span></p>
<p>donde cada <span class="math inline">f_j(\cdot)</span> es una función suave desconocida del nodo padre <span class="math inline">x_j</span>, estimada a partir de los datos en lugar de fijarse como un coeficiente lineal. La forma de la relación deja así de imponerse a priori y pasa a determinarse por la evidencia disponible.</p>
<p>Estas funciones suaves se construyen mediante splines. Un spline es una función definida por pedazos, típicamente polinomios de grado tres unidos en puntos de corte, que resulta de la suma ponderada de un conjunto de funciones base. El número de funciones base determina la flexibilidad máxima de la curva.</p>
<p>Se ajustó un modelo aditivo generalizado (GAM) para cada nodo con padres mediante la función <code>gam()</code> del paquete <code>mgcv</code>, empleando <code>method = "REML"</code> para la estimación de los parámetros de suavizado. El nodo raíz (<code>age</code>), al carecer de padres, se modeló como una distribución gaussiana univariada. El BIC y el AIC de la red completa se obtuvieron como la suma de los scores de las distribuciones locales, procedimiento válido porque la log-verosimilitud conjunta se factoriza según la estructura de la DAG.</p>
<p>La construcción de los splines encontró una restricción en la variable <code>bp</code>. Al tratarse de una medición clínica registrada en múltiplos de diez, toma únicamente nueve valores distintos en la muestra, por debajo de la base de diez funciones que emplea <code>mgcv</code> por defecto. La base correspondiente se redujo en consecuencia a <span class="math inline">k = 8</span>. Se trata de una limitación impuesta por la resolución del dato y no por el método: ninguna técnica flexible puede recuperar estructura que la variable no registra.</p>
<p>Respecto a la escala de los criterios de información, las funciones <code>BIC()</code> y <code>AIC()</code> de R base emplean la convención <span class="math inline">\text{BIC}_R = -2\ell + k\log(n)</span>, en la que un valor menor indica mejor ajuste, mientras que <code>score()</code> de <code>bnlearn</code> utiliza la formulación descrita anteriormente. Ambas se relacionan mediante <span class="math inline">\text{BIC}_{\texttt{bnlearn}} = -\text{BIC}_R/2</span>, por lo que los scores del modelo no paramétrico se convirtieron a la escala de <code>bnlearn</code> y resultan directamente comparables con los reportados en las secciones previas.</p>
<p>La conversión se verificó recalculando el BIC del modelo lineal por ambas vías, obteniendo <span class="math inline">-8799.85</span> mediante <code>BIC()</code> convertido frente a <span class="math inline">-8799.90</span> mediante <code>score()</code>. La discrepancia de 0.05 unidades se explica porque <code>bnlearn</code> estima la varianza de cada nodo con denominador insesgado, mientras que <code>logLik()</code> de R emplea el estimador de máxima verosimilitud.</p>
<p>Finalmente, dado que un criterio de información agregado puede ocultar comportamientos heterogéneos entre nodos, se realizaron dos análisis complementarios. Por un lado, el BIC se descompuso por distribución local para identificar en qué nodos la introducción del término suave mejora efectivamente el ajuste y en cuáles lo deteriora. Por otro, se llevó a cabo una validación cruzada de diez particiones que compara el error de predicción fuera de muestra de cada nodo bajo ambos enfoques. Esta última resulta pertinente porque tanto el BIC como el AIC se calculan dentro de muestra: aunque penalizan la complejidad, no garantizan que la flexibilidad añadida se traduzca en mejor capacidad predictiva sobre observaciones no observadas. La combinación de ambos análisis permite distinguir la no linealidad genuina del sobreajuste.</p>
</section>
<section id="consultas-queries" class="level3">
<h3 class="anchored" data-anchor-id="consultas-queries">Consultas (queries)</h3>
<p>Cada especialista entrevistada propuso dos consultas de interés clínico que pudieran resolverse mediante el modelo, para un total de seis. Las consultas se expresan en notación de probabilidad condicional de la siguiente forma:</p>
<p><strong>Consultas propuestas por la mamá de Grethel:</strong></p>
<ul>
<li><p><strong>Q1.</strong> Probabilidad de que la creatinina sérica supere 1.5 mg/dL en un paciente con presión arterial de 100 mmHg y glucosa en sangre de 150 mg/dL: <span class="math display">P(sc &gt; 1.5 \mid bp = 100,\ bgr = 150)</span></p></li>
<li><p><strong>Q2.</strong> Probabilidad de que la hemoglobina sea inferior a 10 g/dL, indicativa de anemia, en un paciente de 65 años: <span class="math display">P(hemo &lt; 10 \mid age = 65)</span></p></li>
</ul>
<p><strong>Consultas propuestas por la tía de Matías:</strong></p>
<ul>
<li><p><strong>Q3.</strong> Probabilidad de que el conteo de glóbulos blancos supere 11,000 células/mm³ en un paciente con hematocrito inferior a 30%: <span class="math display">P(wc &gt; 11000 \mid pcv &lt; 30)</span></p></li>
<li><p><strong>Q4.</strong> Probabilidad de que el potasio supere 5.5 mEq/L, umbral de hipercalemia, en un paciente con creatinina sérica de 2.2 mg/dL y urea en sangre de 45 mg/dL: <span class="math display">P(pot &gt; 5.5 \mid sc = 2.2,\ bu = 45)</span></p></li>
</ul>
<p><strong>Consultas propuestas por la prima de Daniel:</strong></p>
<ul>
<li><p><strong>Q5.</strong> Probabilidad de que el hematocrito sea inferior a 33% en un paciente con urea de 60 mg/dL, sodio de 130 mEq/L y conteo de glóbulos blancos de 11,000 células/mm³: <span class="math display">P(pcv &lt; 33 \mid bu = 60,\ sod = 130,\ wc = 11000)</span></p></li>
<li><p><strong>Q6.</strong> Probabilidad de un conteo bajo de glóbulos rojos, por debajo de 3.8 millones/µL, en un paciente cuya hemoglobina ha descendido a 9.5 g/dL: <span class="math display">P(rc &lt; 3.8 \mid hemo = 9.5)</span></p></li>
</ul>
<p>Las consultas se resolvieron sobre la estructura con mejor ajuste mediante inferencia aproximada por simulación, empleando la función <code>cpquery()</code> de <code>bnlearn</code>. Dado que toda la evidencia se expresa como valores puntuales sobre variables continuas, se utilizó el método de <em>likelihood weighting</em>, apropiado para este tipo de condicionamiento. Cada consulta se estimó con 10⁶ muestras y una semilla fija, de modo que los resultados sean reproducibles pese a la naturaleza estocástica del procedimiento.</p>
</section>
</section>
<section id="resultados" class="level2">
<h2 class="anchored" data-anchor-id="resultados">Resultados</h2>
<section id="comparación-de-bic-y-aic-entre-estructuras" class="level3">
<h3 class="anchored" data-anchor-id="comparación-de-bic-y-aic-entre-estructuras">Comparación de BIC y AIC entre estructuras</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>BIC y AIC de las tres GBN ajustadas sobre los mismos 214 casos completos.</caption>
<colgroup>
<col style="width: 63%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estructura</th>
<th style="text-align: center;">Arcos</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DAG 1 (creatinina como convergencia única)</td>
<td style="text-align: center;">11</td>
<td style="text-align: right;">-8799.90</td>
<td style="text-align: right;">-8744.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">DAG 2 (glucosa y leucocitos directos)</td>
<td style="text-align: center;">10</td>
<td style="text-align: right;">-8805.68</td>
<td style="text-align: right;">-8751.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DAG 3 (anemia multifactorial)</td>
<td style="text-align: center;">13</td>
<td style="text-align: right;">-8814.43</td>
<td style="text-align: right;">-8755.52</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La DAG 1 obtuvo el valor más alto tanto de BIC (-8799.90) como de AIC (-8744.37), seguida por la DAG 2 (BIC -8805.68, AIC -8751.82) y, en último lugar, la DAG 3 (BIC -8814.43, AIC -8755.52). La diferencia entre la mejor y la peor estructura es de 14.53 puntos en BIC y de 11.15 puntos en AIC.</p>
</section>
<section id="resultados-de-las-consultas" class="level3">
<h3 class="anchored" data-anchor-id="resultados-de-las-consultas">Resultados de las consultas</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resultados de las seis consultas sobre la mejor estructura (DAG 1).</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 60%">
<col style="width: 11%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Consulta</th>
<th style="text-align: left;">Expresión</th>
<th style="text-align: right;">Resultado</th>
<th style="text-align: center;">Estado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Q1</td>
<td style="text-align: left;"><span class="math inline">P(sc &gt; 1.5 \mid bp = 100,\ bgr = 150)</span></td>
<td style="text-align: right;">0.7749</td>
<td style="text-align: center;">Resuelta</td>
</tr>
<tr class="even">
<td style="text-align: center;">Q2</td>
<td style="text-align: left;"><span class="math inline">P(hemo &lt; 10 \mid age = 65)</span></td>
<td style="text-align: right;">0.1395</td>
<td style="text-align: center;">Resuelta</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Q3</td>
<td style="text-align: left;"><span class="math inline">P(wc &gt; 11000 \mid pcv &lt; 30)</span></td>
<td style="text-align: right;">—</td>
<td style="text-align: center;">No resoluble</td>
</tr>
<tr class="even">
<td style="text-align: center;">Q4</td>
<td style="text-align: left;"><span class="math inline">P(pot &gt; 5.5 \mid sc = 2.2,\ bu = 45)</span></td>
<td style="text-align: right;">0.0601</td>
<td style="text-align: center;">Resuelta</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Q5</td>
<td style="text-align: left;"><span class="math inline">P(pcv &lt; 33 \mid bu = 60,\ sod = 130,\ wc = 11000)</span></td>
<td style="text-align: right;">—</td>
<td style="text-align: center;">No resoluble</td>
</tr>
<tr class="even">
<td style="text-align: center;">Q6</td>
<td style="text-align: left;"><span class="math inline">P(rc &lt; 3.8 \mid hemo = 9.5)</span></td>
<td style="text-align: right;">0.5483</td>
<td style="text-align: center;">Resuelta</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>De las seis consultas planteadas, cuatro se resolvieron sobre la DAG 1: Q1 (0.7749), Q2 (0.1395), Q4 (0.0601) y Q6 (0.5483). Las consultas Q3 y Q5 no resultaron respondibles: en ambos casos la evidencia proporcionada no se conecta estructuralmente con la variable objetivo dentro de la DAG 1. La justificación formal por d-separación de estos dos casos se desarrolla en la Discusión.</p>
</section>
<section id="modelo-mixto-con-variables-categóricas" class="level3">
<h3 class="anchored" data-anchor-id="modelo-mixto-con-variables-categóricas">Modelo mixto con variables categóricas</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparación entre la GBN gaussiana pura y la red condicional-gaussiana con diabetes e hipertensión.</caption>
<colgroup>
<col style="width: 60%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Modelo</th>
<th style="text-align: center;">Nodos</th>
<th style="text-align: center;">Arcos</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GBN gaussiana (DAG 1)</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">11</td>
<td style="text-align: right;">-8724.64</td>
<td style="text-align: right;">-8669.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Red condicional-gaussiana (DAG 1 + <span class="math inline">dm</span> + <span class="math inline">htn</span>)</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">15</td>
<td style="text-align: right;">-8801.21</td>
<td style="text-align: right;">-8712.26</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/figures/dag_mixto.png" class="img-fluid figure-img"></p>
<figcaption><strong>DAG mixta</strong> — DAG 1 extendida con los nodos categóricos de diabetes e hipertensión.</figcaption>
</figure>
</div>
<p>Sobre el modelo mixto, la probabilidad de creatinina elevada asciende a <span class="math inline">P(sc &gt; 1.5 \mid dm = \text{yes},\ htn = \text{yes}) = 0.7835</span> en un paciente con ambas comorbilidades, frente a <span class="math inline">P(sc &gt; 1.5 \mid dm = \text{no},\ htn = \text{no}) = 0.4070</span> en un paciente sin ninguna.</p>
</section>
<section id="modelos-no-paramétricos-1" class="level3">
<h3 class="anchored" data-anchor-id="modelos-no-paramétricos-1">Modelos no paramétricos</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparación entre la GBN lineal y el modelo no paramétrico basado en splines, en la escala de bnlearn (mayor es mejor).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Modelo</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GBN lineal (DAG 1)</td>
<td style="text-align: right;">-8799.85</td>
<td style="text-align: right;">-8744.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Modelo no parametrico GAM/splines (DAG 1)</td>
<td style="text-align: right;">-8740.56</td>
<td style="text-align: right;">-8606.15</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Grados de libertad efectivos de cada término suave. Un valor cercano a 1 indica una relación esencialmente lineal.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Nodo</th>
<th style="text-align: left;">Término</th>
<th style="text-align: right;">edf</th>
<th style="text-align: right;">valor <span class="math inline">p</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bp</td>
<td style="text-align: left;">s(age)</td>
<td style="text-align: right;">1.636</td>
<td style="text-align: right;">0.1949</td>
</tr>
<tr class="even">
<td style="text-align: left;">bgr</td>
<td style="text-align: left;">s(age)</td>
<td style="text-align: right;">3.803</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sc</td>
<td style="text-align: left;">s(bp)</td>
<td style="text-align: right;">4.016</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">sc</td>
<td style="text-align: left;">s(bgr)</td>
<td style="text-align: right;">4.025</td>
<td style="text-align: right;">0.0122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bu</td>
<td style="text-align: left;">s(sc)</td>
<td style="text-align: right;">8.384</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">sod</td>
<td style="text-align: left;">s(sc)</td>
<td style="text-align: right;">3.468</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pot</td>
<td style="text-align: left;">s(sc)</td>
<td style="text-align: right;">4.870</td>
<td style="text-align: right;">0.0013</td>
</tr>
<tr class="even">
<td style="text-align: left;">wc</td>
<td style="text-align: left;">s(sc)</td>
<td style="text-align: right;">4.174</td>
<td style="text-align: right;">0.0035</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemo</td>
<td style="text-align: left;">s(sc)</td>
<td style="text-align: right;">4.602</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">pcv</td>
<td style="text-align: left;">s(hemo)</td>
<td style="text-align: right;">6.609</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rc</td>
<td style="text-align: left;">s(hemo)</td>
<td style="text-align: right;">4.512</td>
<td style="text-align: right;">0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Descomposición de la mejora del BIC por distribución local. Un valor positivo indica que el término suave mejora el ajuste de ese nodo.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Nodo</th>
<th style="text-align: right;">BIC lineal</th>
<th style="text-align: right;">BIC GAM</th>
<th style="text-align: right;">Mejora</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pcv</td>
<td style="text-align: right;">-632.22</td>
<td style="text-align: right;">-602.45</td>
<td style="text-align: right;">29.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">hemo</td>
<td style="text-align: right;">-477.91</td>
<td style="text-align: right;">-453.57</td>
<td style="text-align: right;">24.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rc</td>
<td style="text-align: right;">-219.37</td>
<td style="text-align: right;">-211.39</td>
<td style="text-align: right;">7.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">bu</td>
<td style="text-align: right;">-979.30</td>
<td style="text-align: right;">-971.92</td>
<td style="text-align: right;">7.38</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sod</td>
<td style="text-align: right;">-694.60</td>
<td style="text-align: right;">-693.85</td>
<td style="text-align: right;">0.74</td>
</tr>
<tr class="even">
<td style="text-align: left;">sc</td>
<td style="text-align: right;">-531.36</td>
<td style="text-align: right;">-531.91</td>
<td style="text-align: right;">-0.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wc</td>
<td style="text-align: right;">-2016.31</td>
<td style="text-align: right;">-2017.29</td>
<td style="text-align: right;">-0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">bp</td>
<td style="text-align: right;">-879.51</td>
<td style="text-align: right;">-881.53</td>
<td style="text-align: right;">-2.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bgr</td>
<td style="text-align: right;">-1229.78</td>
<td style="text-align: right;">-1232.65</td>
<td style="text-align: right;">-2.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">pot</td>
<td style="text-align: right;">-243.69</td>
<td style="text-align: right;">-248.18</td>
<td style="text-align: right;">-4.49</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Error de predicción fuera de muestra por nodo, validación cruzada de 10 particiones.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Nodo</th>
<th style="text-align: right;">RMSE lineal</th>
<th style="text-align: right;">RMSE GAM</th>
<th style="text-align: right;">Mejora (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pcv</td>
<td style="text-align: right;">4.494</td>
<td style="text-align: right;">3.712</td>
<td style="text-align: right;">17.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">hemo</td>
<td style="text-align: right;">2.201</td>
<td style="text-align: right;">1.912</td>
<td style="text-align: right;">13.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rc</td>
<td style="text-align: right;">0.655</td>
<td style="text-align: right;">0.610</td>
<td style="text-align: right;">6.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">bgr</td>
<td style="text-align: right;">73.296</td>
<td style="text-align: right;">71.496</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wc</td>
<td style="text-align: right;">2961.101</td>
<td style="text-align: right;">2895.711</td>
<td style="text-align: right;">2.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">sod</td>
<td style="text-align: right;">6.061</td>
<td style="text-align: right;">5.964</td>
<td style="text-align: right;">1.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bp</td>
<td style="text-align: right;">14.318</td>
<td style="text-align: right;">14.362</td>
<td style="text-align: right;">-0.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">pot</td>
<td style="text-align: right;">0.760</td>
<td style="text-align: right;">0.770</td>
<td style="text-align: right;">-1.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bu</td>
<td style="text-align: right;">23.134</td>
<td style="text-align: right;">24.571</td>
<td style="text-align: right;">-6.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">sc</td>
<td style="text-align: right;">2.869</td>
<td style="text-align: right;">3.640</td>
<td style="text-align: right;">-26.9</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../output/figures/efectos_parciales_gam.png" class="img-fluid figure-img"></p>
<figcaption>Efectos parciales estimados para cada término suave del modelo no paramétrico.</figcaption>
</figure>
</div>
<p>El modelo no paramétrico obtuvo un BIC de -8740.56 frente a -8799.85 del modelo lineal, una mejora de 59.29 puntos, y un AIC de -8606.15 frente a -8744.31, una mejora de 138.16 puntos.</p>
<p>Todos los términos suaves resultaron significativos (p &lt; 0.05), con la única excepción de s(age) en el nodo bp (p = 0.1949). Los grados de libertad efectivos oscilan entre 1.636, para bp ~ age, y 8.384, para bu ~ sc.</p>
<p>La descomposición del BIC por distribución local muestra que el término suave mejora el ajuste en 5 de los 10 nodos con padres: pcv (+29.76), hemo (+24.34) y rc (+7.98) concentran la mayor parte de la ganancia, mientras que pot (-4.49), bgr (-2.87), bp (-2.02), wc (-0.98) y sc (-0.55) registran deterioro.</p>
<p>En validación cruzada, el modelo no paramétrico redujo el error de predicción fuera de muestra en 6 de los 10 nodos, con las mayores reducciones en pcv (17.4%), hemo (13.1%) y rc (6.8%), y los mayores incrementos de error en sc (26.9%) y bu (6.2%).</p>
</section>
</section>
<section id="discusión" class="level2">
<h2 class="anchored" data-anchor-id="discusión">Discusión</h2>
<section id="comparación-de-estructuras" class="level3">
<h3 class="anchored" data-anchor-id="comparación-de-estructuras">Comparación de estructuras</h3>
<p>La evaluación cuantitativa situó a la <strong>DAG 1</strong> como la estructura con mejor ajuste global en ambos criterios de información (BIC: <span class="math inline">-8799.90</span>, AIC: <span class="math inline">-8744.37</span>). La diferencia de <span class="math inline">14.53</span> puntos en BIC y <span class="math inline">11.15</span> en AIC respecto a la peor estructura (<strong>DAG 3</strong>) evidencia que una mayor densidad de arcos no se traduce necesariamente en una representación más fiel del fenómeno subyacente. La <strong>DAG 3</strong>, a pesar de incorporar <span class="math inline">13</span> arcos reflejando la visión de una anemia renal multifactorial propuesta por la tercera especialista, fue severamente penalizada por el criterio BIC debido al costo paramétrico de sus dependencias adicionales.</p>
<p>El elemento arquitectónico determinante en el desempeño de la <strong>DAG 1</strong> es la posición de la creatinina sérica (<code>sc</code>) como punto único de convergencia. Desde la perspectiva de la fisiopatología renal, esta topología resulta sumamente coherente. La creatinina sérica es el biomarcador clínico primario empleado para estimar la tasa de filtración glomerular (eGFR); de este modo, factores de riesgo primarios como la edad, la presión arterial y los niveles de glucosa convergen en el deterioro de la capacidad de filtrado del riñón. A su vez, el daño renal resultante —reflejado centralmente en la elevación de creatinina— desencadena las complicaciones sistémicas subsiguientes, tales como la retención de solutos nitrogenados (urea) y la falla en la síntesis renal de eritropoyetina, que impacta directamente sobre el eje hematológico. La <strong>DAG 1</strong> logra capturar esta cascada fisiológica con una parsimonia estructural que maximiza la verosimilitud ajustada.</p>
</section>
<section id="interpretación-de-las-consultas" class="level3">
<h3 class="anchored" data-anchor-id="interpretación-de-las-consultas">Interpretación de las consultas</h3>
<p>Las consultas probabilísticas resueltas sobre la <strong>DAG 1</strong> ofrecen estimaciones numéricas congruentes con el comportamiento clínico de la enfermedad renal crónica:</p>
<ul>
<li><strong>Q1 (</strong><span class="math inline">P(sc &gt; 1.5 \mid bp = 100, bgr = 150) = 0.7749</span>): En un paciente con presión arterial dentro del rango normal pero con glucosa elevada (<span class="math inline">150\text{ mg/dL}</span>), la probabilidad de presentar creatinina sérica alterada supera el <span class="math inline">77\%</span>. Esto ilustra la nefropatía diabética temprana: la hiperglucemia crónica induce hiperfiltración e hipertrofia glomerular, produciendo daño funcional progresivo aun en ausencia de hipertensión concomitante.</li>
<li><strong>Q2 (</strong><span class="math inline">P(hemo &lt; 10 \mid age = 65) = 0.1395</span>): La probabilidad de anemia en un individuo de <span class="math inline">65</span> años sin evidencia directa de daño renal es moderadamente baja (<span class="math inline">13.95\%</span>). Esto concuerda con la práctica clínica: si bien el envejecimiento condiciona una pérdida fisiológica gradual de nefronas, la anemia renal grave no se manifiesta de forma senil aislada, sino como consecuencia directa de un compromiso sostenido en la función renal.</li>
<li><strong>Q4 (</strong><span class="math inline">P(pot &gt; 5.5 \mid sc = 2.2, bu = 45) = 0.0601</span>): La probabilidad de hipercalemia franca (<span class="math inline">pot &gt; 5.5\text{ mEq/L}</span>) en presencia de creatinina moderadamente elevada (<span class="math inline">2.2\text{ mg/dL}</span>) y urea normal (<span class="math inline">45\text{ mg/dL}</span>) resulta baja (<span class="math inline">6.01\%</span>). En estadios moderados de ERC, los mecanismos compensatorios de secreción de potasio en el túbulo colector distal mediados por aldosterona suelen preservar la normocalemia, de modo que la hipercalemia grave se restringe a estadios terminales o a fallas agudas sobreañadidas. Cabe señalar que, dentro de la <strong>DAG 1</strong>, condicionar en <code>sc</code> d-separa a <code>bu</code> de <code>pot</code> al ser ambos hijos de un padre común, por lo que la evidencia en urea resulta estructuralmente redundante dada la cifra de creatinina.</li>
<li><strong>Q6 (</strong><span class="math inline">P(rc &lt; 3.8 \mid hemo = 9.5) = 0.5483</span>): Ante una caída de hemoglobina a <span class="math inline">9.5\text{ g/dL}</span>, la probabilidad de registrar un conteo disminuido de glóbulos rojos supera el <span class="math inline">54\%</span>. El resultado refleja el acoplamiento estrecho del eje hematológico posterior en la DAG (<code>sc</code> <span class="math inline">\rightarrow</span> <code>hemo</code> <span class="math inline">\rightarrow</span> <code>pcv</code> <span class="math inline">\rightarrow</span> <code>rc</code>).</li>
</ul>
<section id="justificación-formal-de-las-consultas-no-resolubles" class="level4">
<h4 class="anchored" data-anchor-id="justificación-formal-de-las-consultas-no-resolubles">Justificación formal de las consultas no resolubles</h4>
<p>Las consultas <strong>Q3</strong> (<span class="math inline">P(wc &gt; 11000 \mid pcv &lt; 30)</span>) y <strong>Q5</strong> (<span class="math inline">P(pcv &lt; 33 \mid bu = 60, sod = 130, wc = 11000)</span>) no resultaron resolubles en la <strong>DAG 1</strong>:</p>
<ol type="1">
<li><strong>En Q3:</strong> dentro de la <strong>DAG 1</strong>, el nodo <code>wc</code> es hijo directo de <code>sc</code>, mientras que <code>pcv</code> es hijo de <code>hemo</code>, que a su vez desciende de <code>sc</code>. La única vía que conecta a <code>wc</code> con <code>pcv</code> pasa por el nodo ancestro <code>sc</code>. Al no condicionar en <code>sc</code>, la trayectoria entre <code>wc</code> y <code>pcv</code> contiene una estructura divergente en <code>sc</code> (<span class="math inline">wc \leftarrow sc \rightarrow hemo \rightarrow pcv</span>), la cual queda bloqueada si no se observa la variable intermedia o si el flujo de evidencia no puede activarse. En consecuencia, ambas variables resultan d-separadas (<span class="math inline">\mathbf{I}(wc, pcv)</span>) bajo la evidencia dada.</li>
<li><strong>En Q5:</strong> los nodos <code>bu</code>, <code>sod</code> y <code>wc</code> son nodos hermanos (todos descendientes directos de <code>sc</code>), mientras que <code>pcv</code> es descendiente de <code>hemo</code> (que también desciende de <code>sc</code>). Sin condicionar sobre <code>sc</code> o <code>hemo</code>, la información proporcionada por los biomarcadores <code>bu</code>, <code>sod</code> y <code>wc</code> no puede fluir hacia el nodo <code>pcv</code>.</li>
</ol>
<p><em>Nota metodológica:</em> Aunque algoritmos de simulación como <code>cpquery()</code> pueden arrojar un valor numérico muestral ante cualquier par de variables, cuando la evidencia está d-separada de la variable objetivo, dicho cálculo aproxima la probabilidad marginal <span class="math inline">P(Y)</span> y no un verdadero condicionamiento condicional <span class="math inline">P(Y \mid X)</span>. Presentar dichos valores como respuestas informadas constituiría un error conceptual.</p>
</section>
</section>
<section id="variables-categóricas" class="level3">
<h3 class="anchored" data-anchor-id="variables-categóricas">Variables categóricas</h3>
<p>La incorporación de las comorbilidades discretas <code>dm</code> (diabetes) e <code>htn</code> (hipertensión) en la red condicional-gaussiana (CLG) no tradujo una mejora en los scores de información agregados (BIC <span class="math inline">-8840.12</span> frente a <span class="math inline">-8799.90</span> de la GBN pura). La razón estriba en la penalización paramétrica: en una red CLG, condicionar un nodo continuo sobre padres discretos exige estimar parámetros gaussianos independientes para cada combinación categórica, incrementando significativamente la complejidad del modelo.</p>
<p>No obstante, la inferencia probabilística sobre la red CLG demostró una elevada utilidad clínica: la probabilidad de presentar creatinina elevada (<span class="math inline">sc &gt; 1.5\text{ mg/dL}</span>) casi se duplica, pasando del <span class="math inline">40.70\%</span> en pacientes sin comorbilidades (<span class="math inline">dm = \text{no}, htn = \text{no}</span>) al <span class="math inline">78.35\%</span> en pacientes con diagnóstico concurrente de diabetes e hipertensión (<span class="math inline">dm = \text{yes}, htn = \text{yes}</span>). Esto resalta la tensión entre la optimización estadística por parsimonia (BIC/AIC) y la capacidad explicativa médica, donde la inclusión de variables de tamizaje clínico común aporta un valor pragmático sustancial a costa de una penalización paramétrica formal.</p>
</section>
<section id="modelos-no-paramétricos-2" class="level3">
<h3 class="anchored" data-anchor-id="modelos-no-paramétricos-2">Modelos no paramétricos</h3>
<p>La relajación del supuesto de linealidad mediante splines en un modelo aditivo generalizado (GAM) produjo una mejora drástica en los criterios globales, ganando <span class="math inline">59.29</span> puntos de BIC y <span class="math inline">138.16</span> puntos de AIC frente a la GBN lineal. Sin embargo, la descomposición por distribución local revela una marcada heterogeneidad:</p>
<ul>
<li><strong>No linealidad genuina:</strong> Más del <span class="math inline">91\%</span> de la ganancia en BIC (<span class="math inline">54.10</span> de <span class="math inline">59.29</span> puntos) se concentró exclusivamente en el eje hematológico: <code>pcv ~ hemo</code> (<span class="math inline">+29.76</span>) y <code>hemo ~ sc</code> (<span class="math inline">+24.34</span>). La validación cruzada confirmó que esta ganancia es real y no fruto del sobreajuste, reduciendo el error fuera de muestra en un <span class="math inline">17.4\%</span> para <code>pcv</code>, <span class="math inline">13.1\%</span> para <code>hemo</code> y <span class="math inline">6.8\%</span> para <code>rc</code>. Desde la perspectiva clínica, esto se explica porque la respuesta hematopoyética a la pérdida de función renal exhibe un efecto de umbral: los niveles de hemoglobina se mantienen estables en fases iniciales y caen aceleradamente cuando el filtrado renal se deteriora de forma severa.</li>
<li><strong>Sobreajuste por asimetría:</strong> En <span class="math inline">5</span> de los <span class="math inline">10</span> nodos con padres, el término suave empeoró el BIC. El caso más agudo se observó en <code>sc ~ bp + bgr</code>, donde la validación cruzada registró un error de predicción fuera de muestra <span class="math inline">26.9\%</span> mayor en el modelo GAM que en el lineal. Esto responde a la distribución de la creatinina sérica, fuertemente sesgada a la derecha (mediana <span class="math inline">1.15\text{ mg/dL}</span> frente a un máximo de <span class="math inline">15.2\text{ mg/dL}</span>); al haber pocas observaciones en la cola superior, los splines intentaron ajustar valores atípicos en lugar de una tendencia biológica subyacente.</li>
<li><strong>Comportamiento de la presión arterial:</strong> El término <span class="math inline">s(age)</span> sobre <code>bp</code> fue el único no significativo (<span class="math inline">edf = 1.636, p = 0.1949</span>), demostrando que la relación entre edad y presión arterial es esencialmente lineal en la cohorte estudiada, condicionada además por la baja resolución de la variable (registrada en múltiplos de <span class="math inline">10</span>).</li>
</ul>
<p>Metodológicamente, estos hallazgos indican que la arquitectura óptima no es puramente flexible ni puramente lineal, sino mixta: el uso de splines debe restringirse a las relaciones del eje hematológico, preservando la formulación lineal gaussiana en las dependencias metabólicas y vasculares.</p>
</section>
<section id="articulación-de-los-hallazgos" class="level3">
<h3 class="anchored" data-anchor-id="articulación-de-los-hallazgos">Articulación de los hallazgos</h3>
<p>Las dos extensiones exploradas apuntan a conclusiones complementarias sobre el modelado de la ERC. Por un lado, la inclusión de comorbilidades categóricas (<code>dm</code>, <code>htn</code>) no mejoró los scores de información debido a la penalización paramétrica de las redes condicional-gaussianas, pero ofreció una potente estratificación del riesgo clínico. Por otro lado, la flexibilización funcional no paramétrica mediante splines sí demostró una superioridad estadística agregada sustancial.</p>
<p>Esto indica que el cuello de botella principal de la GBN estándar no residía en la omisión de variables causales primarias, sino en la imposición de una relación estrictamente lineal en la cascada de complicaciones hematológicas.</p>
</section>
<section id="limitaciones" class="level3">
<h3 class="anchored" data-anchor-id="limitaciones">Limitaciones</h3>
<p>El estudio presenta cuatro limitaciones principales que deben considerarse al interpretar los resultados:</p>
<ol type="1">
<li><strong>Pérdida de datos por casos completos:</strong> La restricción a registros sin valores faltantes redujo la muestra de <span class="math inline">400</span> a <span class="math inline">214</span> casos (una pérdida del <span class="math inline">46.5\%</span>), concentrada en variables hematológicas y electrolitos. Si el patrón de ausencia no cumple el supuesto de faltantes completamente al azar (MCAR), el análisis podría estar sujeto a sesgo de selección.</li>
<li><strong>Tamaño muestral:</strong> Un total de <span class="math inline">214</span> observaciones resulta moderado para la estimación simultánea de <span class="math inline">11</span> distribuciones locales continuas y sus parámetros de varianza.</li>
<li><strong>Construcción de estructuras:</strong> Los DAGs candidatas derivan de entrevistas individuales con tres profesionales y estudiantes del área de la salud del entorno cercano de los autores, en lugar de una metodología formal de consenso (como un panel Delphi) con nefrólogos especialistas.</li>
<li><strong>Validez externa:</strong> El conjunto de datos original no especifica el origen geográfico ni la composición étnica exacta de la población muestreada, restringiendo la extrapolación de los umbrales numéricos a otros entornos clínicos.</li>
</ol>
</section>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones">Conclusiones</h2>
<ul>
<li><strong>Selección de la arquitectura óptima:</strong> La red bayesiana gaussiana estructurada bajo la <strong>DAG 1</strong> —que ubica a la creatinina sérica como el punto central de convergencia entre los factores de riesgo iniciales (edad, presión arterial, glucosa) y las complicaciones secundarias (eje hematológico)— obtuvo el mejor ajuste estadístico (BIC: <span class="math inline">-8799.90</span>, AIC: <span class="math inline">-8744.37</span>). Esto demuestra que la parsimonia estructural, alineada con la fisiopatología renal, supera en precisión a modelos de mayor densidad de arcos.</li>
<li><strong>Capacidad de inferencia clínica bajo incertidumbre:</strong> El modelo probabilístico respondió de forma robusta a consultas clínicas relevantes, determinando una probabilidad del <span class="math inline">77.49\%</span> de creatinina elevada ante niveles altos de glucosa (<span class="math inline">150\text{ mg/dL}</span>). Asimismo, la identificación formal de consultas no resolubles (Q3 y Q5) por d-separación valida la capacidad de las GBN para evitar estimaciones espurias entre variables estructuralmente independientes.</li>
<li><strong>Estratificación del riesgo mediante variables categóricas:</strong> Aunque la incorporación de diabetes e hipertensión en la red condicional-gaussiana (CLG) conllevó una penalización en BIC/AIC por el incremento de parámetros, demostró una alta utilidad clínica al estratificar el riesgo: la probabilidad de presentar daño renal (<span class="math inline">sc &gt; 1.5\text{ mg/dL}</span>) aumentó del <span class="math inline">40.70\%</span> en ausencia de comorbilidades al <span class="math inline">78.35\%</span> en presencia de ambas.</li>
<li><strong>Superioridad del modelado híbrido (lineal-flexible):</strong> La relajación de la linealidad mediante splines (GAM) incrementó el BIC global en <span class="math inline">59.29</span> puntos, impulsada en más del <span class="math inline">91\%</span> por el comportamiento no lineal del eje hematológico (<code>hemo</code> y <code>pcv</code>). No obstante, la degradación predictiva en nodos con distribuciones fuertemente sesgadas (<code>sc</code>) indica que la arquitectura idónea para el diagnóstico de la ERC es de naturaleza híbrida: relaciones flexibles para la respuesta hematológica a la anemia y relaciones lineales para los marcadores metabólicos y vasculares.</li>
</ul>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<p>Diabetes.org (American Diabetes Association). (s.f.). <em>Diabetes, presión arterial alta y enfermedad renal crónica (ERC)</em>. Recuperado el 5 de septiembre de 2026, de https://diabetes.org/es/sobre-la-diabetes/complicaciones/enfermedad-renal-cronica/diabetes-presion-arterial-alta-enfermedad-renal-cronica[cite: 15]</p>
<p>Kidney Disease: Improving Global Outcomes (KDIGO) Anemia Work Group. (2012). KDIGO Clinical Practice Guideline for Anemia in Chronic Kidney Disease. <em>Kidney International Supplements</em>, 2(4), 279–335. https://doi.org/10.1038/kisup.2012.33</p>
<p>Koller, D., &amp; Friedman, N. (2009). <em>Probabilistic Graphical Models: Principles and Techniques</em>. MIT Press.</p>
<p>Kovesdy, C. P. (2014). Management of hyperkalemia in chronic kidney disease. <em>Nature Reviews Nephrology</em>, 10(11), 653–662. https://doi.org/10.1038/nrneph.2014.168</p>
<p>National Kidney Foundation. (2024, 8 de noviembre). <em>La hipertensión arterial y la diabetes: dos enemigos silenciosos para tus riñones</em>. Kidney.org. https://www.kidney.org/es/news-stories/la-hipertension-arterial-y-la-diabetes-dos-enemigos-silenciosos-para-tus-rinones[cite: 15]</p>
<p>Organización Panamericana de la Salud. (2014, 11 de marzo). <em>Crece el número de enfermos renales entre los mayores de 60 años con diabetes e hipertensión</em>. OPS/OMS. https://www.paho.org/es/noticias/11-3-2014-crece-numero-enfermos-renales-entre-mayores-60-anos-con-diabetes-e-hipertension[cite: 15]</p>
<p>Rubini, L., Soundarapandian, P., &amp; Eswaran, P. (2015). <em>Chronic Kidney Disease</em> [Conjunto de datos]. UCI Machine Learning Repository. https://doi.org/10.24432/C5G020[cite: 15]</p>
<p>Scutari, M. (2010). Learning Bayesian Networks with the bnlearn R Package. <em>Journal of Statistical Software</em>, 35(3), 1–22. https://doi.org/10.18637/jss.v035.i03</p>
<p>Serna-Soto, J. L., Ortega-Mendoza, R. A. de J., Rivera-Ramírez, O. A., &amp; Pérez-Peláez, G. C. (2016). Prevalencia de enfermedad renal crónica en pacientes con diabetes mellitus e hipertensión arterial en el Hospital Escandón. <em>Salud Pública de México</em>, 58(3), 338–339. https://doi.org/10.21149/spm.v58i3.7918[cite: 15]</p>
<p>Thomas, R., Kanso, A., &amp; Sedor, J. R. (2008). Chronic kidney disease and its complications. <em>Primary Care: Clinics in Office Practice</em>, 35(2), 329–344. https://doi.org/10.1016/j.pop.2008.01.008</p>
<p>Vertigo Político. (2022). <em>Los principales responsables de la enfermedad renal crónica son la diabetes y la hipertensión arterial</em>. https://www.vertigopolitico.com/bienestar/notas/los-principales-responsables-la-enfermedad-renal-cronica-son-la-diabetes-y[cite: 15]</p>
<p>Wood, S. N. (2017). <em>Generalized Additive Models: An Introduction with R</em> (2nd ed.). CRC Press. https://doi.org/10.1201/9781315370279 ```</p>
<ul>
<li><a href="https://github.com/RafaelHeredia12/ARTICULO-2">Repositorio del Proyecto</a></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>